# Collector specific configuration
base_url: "https://api.climatetrace.org"

gases: "/v7/definitions/gases"

endpoints:
  sources:
    url: "/v7/sources"
    min_year: 2021
  source_by_id:
    url: "/v7/sources/:id"
    min_year: 2021
  aggregate:
    url: "/v7/sources/emissions"
    min_year: 2015

dataset_title: "Climate TRACE GHG and non-GHG Emissions Inventory"

tags:
  - air pollutants
  - environment
  - geodata
  - greenhouse gas emissions
  - points of interest-poi
